-- Free image-generation models for the Mint AI Engine Panel.
-- These route through the Pollinations public image endpoint in the backend.

INSERT INTO ai_models
  (
    openrouter_id,
    name,
    description,
    provider_name,
    supported_tools,
    tier,
    cost_per_1k_tokens,
    context_window,
    tags,
    is_trending,
    is_active,
    sort_order,
    supports_refs,
    supports_thinking_level,
    supports_google_search,
    is_beta,
    avg_latency_seconds,
    latency_range,
    is_unlimited_tier,
    best_for,
    provider_display_name,
    icon_key
  )
VALUES
  (
    'pollinations/flux',
    'Pollinations Flux',
    'Free image generation for concepts, social drafts, and quick creative exploration.',
    'Pollinations',
    ARRAY['image']::ai_tool_type[],
    'free',
    0,
    0,
    ARRAY['image','free','concept','social','pollinations'],
    true,
    true,
    1,
    false,
    false,
    false,
    true,
    12,
    '~12s',
    '{"1K": true, "2K": true, "4K": true}'::jsonb,
    ARRAY['quick concepts','social images','mood exploration'],
    'Pollinations',
    'sparkles'
  ),
  (
    'pollinations/turbo',
    'Pollinations Turbo',
    'Free fast image generation for rough drafts and prompt testing.',
    'Pollinations',
    ARRAY['image']::ai_tool_type[],
    'free',
    0,
    0,
    ARRAY['image','free','fast','draft','pollinations'],
    true,
    true,
    2,
    false,
    false,
    false,
    true,
    8,
    '~8s',
    '{"1K": true, "2K": true, "4K": true}'::jsonb,
    ARRAY['fast drafts','caption visuals','prompt testing'],
    'Pollinations',
    'zap'
  )
ON CONFLICT (openrouter_id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  provider_name = EXCLUDED.provider_name,
  supported_tools = EXCLUDED.supported_tools,
  tier = EXCLUDED.tier,
  cost_per_1k_tokens = EXCLUDED.cost_per_1k_tokens,
  context_window = EXCLUDED.context_window,
  tags = EXCLUDED.tags,
  is_trending = EXCLUDED.is_trending,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order,
  supports_refs = EXCLUDED.supports_refs,
  supports_thinking_level = EXCLUDED.supports_thinking_level,
  supports_google_search = EXCLUDED.supports_google_search,
  is_beta = EXCLUDED.is_beta,
  avg_latency_seconds = EXCLUDED.avg_latency_seconds,
  latency_range = EXCLUDED.latency_range,
  is_unlimited_tier = EXCLUDED.is_unlimited_tier,
  best_for = EXCLUDED.best_for,
  provider_display_name = EXCLUDED.provider_display_name,
  icon_key = EXCLUDED.icon_key,
  updated_at = NOW();
