-- Curate Mint AI image models to the approved production list.
-- Non-destructive: old image models keep their rows for historical generations,
-- but no longer advertise the image capability in the Engine Panel.

WITH approved_image_models(openrouter_id) AS (
  VALUES
    ('google/gemini-3.1-flash-image'),
    ('google/gemini-3-pro-image'),
    ('bytedance-seed/seedream-4.5'),
    ('replicate/bytedance/seedream-5-lite')
)
UPDATE ai_models
SET
  supported_tools = array_remove(supported_tools, 'image'::ai_tool_type),
  is_trending = false,
  updated_at = NOW()
WHERE supported_tools @> ARRAY['image']::ai_tool_type[]
  AND openrouter_id NOT IN (SELECT openrouter_id FROM approved_image_models);

INSERT INTO ai_models
  (
    openrouter_id,
    name,
    description,
    provider_name,
    supported_tools,
    tier,
    cost_per_1k_tokens,
    context_window,
    tags,
    is_trending,
    is_active,
    sort_order,
    supports_refs,
    supports_thinking_level,
    supports_google_search,
    is_beta,
    avg_latency_seconds,
    latency_range,
    is_unlimited_tier,
    best_for,
    provider_display_name,
    icon_key
  )
VALUES
  (
    'google/gemini-3.1-flash-image',
    'Nano Banana 2',
    'Google Gemini 3.1 Flash Image through OpenRouter for balanced creative image generation.',
    'Google',
    ARRAY['image']::ai_tool_type[],
    'standard',
    2,
    32768,
    ARRAY['image','google','nano-banana','balanced','openrouter'],
    true,
    true,
    10,
    true,
    false,
    false,
    false,
    18,
    '~18s',
    '{"1K": false, "2K": false, "4K": false}'::jsonb,
    ARRAY['social creatives','campaign visuals','brand concepts'],
    'Google',
    'sparkles'
  ),
  (
    'google/gemini-3-pro-image',
    'Nano Banana Pro',
    'Google Gemini 3 Pro Image through OpenRouter for higher-quality creative direction and complex prompts.',
    'Google',
    ARRAY['image']::ai_tool_type[],
    'premium',
    5,
    65536,
    ARRAY['image','google','nano-banana-pro','premium','openrouter'],
    true,
    true,
    20,
    true,
    false,
    false,
    false,
    34,
    '~34s',
    '{"1K": false, "2K": false, "4K": false}'::jsonb,
    ARRAY['premium campaign visuals','complex scenes','polished final concepts'],
    'Google',
    'sparkles'
  ),
  (
    'bytedance-seed/seedream-4.5',
    'Seedream 4.5',
    'ByteDance Seedream 4.5 through OpenRouter for high-quality creative image generation.',
    'ByteDance',
    ARRAY['image']::ai_tool_type[],
    'premium',
    4,
    4000,
    ARRAY['image','bytedance','seedream','openrouter','premium'],
    true,
    true,
    25,
    true,
    false,
    false,
    false,
    30,
    '~30s',
    '{"1K": false, "2K": false, "4K": false}'::jsonb,
    ARRAY['brand visuals','premium drafts','campaign concepts'],
    'ByteDance',
    'image'
  ),
  (
    'replicate/bytedance/seedream-5-lite',
    'Seedream 5 Lite',
    'ByteDance Seedream 5 Lite through Replicate for fast high-resolution image generation with reference support.',
    'Replicate',
    ARRAY['image']::ai_tool_type[],
    'standard',
    3,
    4000,
    ARRAY['image','bytedance','seedream','replicate','refs'],
    true,
    true,
    30,
    true,
    false,
    false,
    false,
    24,
    '~24s',
    '{"1K": false, "2K": false, "4K": false}'::jsonb,
    ARRAY['reference-led images','high-resolution drafts','product scenes'],
    'ByteDance',
    'image'
  )
ON CONFLICT (openrouter_id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  provider_name = EXCLUDED.provider_name,
  supported_tools = EXCLUDED.supported_tools,
  tier = EXCLUDED.tier,
  cost_per_1k_tokens = EXCLUDED.cost_per_1k_tokens,
  context_window = EXCLUDED.context_window,
  tags = EXCLUDED.tags,
  is_trending = EXCLUDED.is_trending,
  is_active = EXCLUDED.is_active,
  sort_order = EXCLUDED.sort_order,
  supports_refs = EXCLUDED.supports_refs,
  supports_thinking_level = EXCLUDED.supports_thinking_level,
  supports_google_search = EXCLUDED.supports_google_search,
  is_beta = EXCLUDED.is_beta,
  avg_latency_seconds = EXCLUDED.avg_latency_seconds,
  latency_range = EXCLUDED.latency_range,
  is_unlimited_tier = EXCLUDED.is_unlimited_tier,
  best_for = EXCLUDED.best_for,
  provider_display_name = EXCLUDED.provider_display_name,
  icon_key = EXCLUDED.icon_key,
  updated_at = NOW();
